version: '3.3'
services:

    todo_mysql:
        image: mysql
        volumes: 
            - ./db/:/docker-entrypoint-initdb.d/
        environment: 
            - "MYSQL_ROOT_PASSWORD=123456"
        ports: 
            - "3306:3306"

    todo_mongodb:
        image:  mongo
        ports: 
            - "27017:27017"

    todo_rabbitmq:
        hostname: todo_rabbitmq_host
        image: rabbitmq:management
        environment: 
            - RABBITMQ_DEFAULT_USER=admin
            - RABBITMQ_DEFAULT_PASS=123456
        ports:
            - "5672:5672"
            - "15672:15672"

# networks:
#   default:
#       external: true
#       name: todo-app-test
