services:

    dev_database_viewer:
        image: mongo-express
        ports:
            - "8081:8081"
        environment:
            ME_CONFIG_MONGODB_SERVER: dev_db_host2
            ME_CONFIG_BASICAUTH_ENABLED: "true"
            ME_CONFIG_MONGODB_ADMINUSERNAME: root
            ME_CONFIG_MONGODB_ADMINPASSWORD: 123456
            ME_CONFIG_MONGODB_URL: mongodb://root:123456@dev_db_host2:27017/
        networks:
            - my_dev_apps

networks:
    my_dev_apps:
        external: true