name: build-npm-package

on:
  # push:
  #   branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]

  workflow_dispatch:
    inputs:
      pkg_version:
        description: "NPM package version"
        required: true
        default: "0.0.0"
      test_mode:
        description: "Flag value of test mode"
        required: false
        default: "true"

jobs:
  build-package:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: echo github ref
        run: echo ${{ github.ref }}

      - name: use node
        uses: actions/setup-node@v1
        with:
          node-version: "20.x"
          registry-url: https://registry.npmjs.org/
          
      # - name: Run a one-line script
      #   run: echo Hello, world!

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          node -v
          npm -v
          yarn -v
          ls
          pwd

      - name: Install package
        run: cd ./service-typescript && yarn install
  
      - name: ESLint Check
        run: cd ./service-typescript && yarn lint

      - name: Unit Test Check
        run: cd ./service-typescript && yarn test-cc
      
      - name: 'Change version'
        uses: reedyuk/npm-version@1.1.1
        with:
          version: ${{ github.event.inputs.pkg_version }}
          package: 'service-typescript/'

      - name: 'Print version'
        run: cd ./service-typescript && cat package.json

      - name: Build and Bubble Package
        run: cd ./service-typescript && yarn release

      - name: Prepare tar file
        run: cd ./service-typescript/dist && npm pack

      - name: List files
        run: ls ./service-typescript/dist

      - name: Publish package
        run: cd ./service-typescript/dist && npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}} 