name: tester-run

on:

  workflow_dispatch:
    inputs:
      pkg_version:
        description: "Angular UI Package version"
        required: true
        default: "0.0.0"
      test_mode:
        description: "Flag value of test mode"
        required: false
        default: "true"
  
  push:
    tags:
      - 'v*'

jobs:
  build-package:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4

      - name: echo github ref
        run: echo ${{ github.ref }}

      # - name: get version
      #   id: get_version
      #   run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
        
      # - name: echo version
      #   run: echo ${{ steps.get_version.outputs.VERSION }}

      - name: use node
        uses: actions/setup-node@v1
        with:
          node-version: "20.x"
          registry-url: https://registry.npmjs.org/

      - name: Install package
        run: cd ./web-apps/angular-apps && yarn install
      
      - name: 'Change version'
        uses: reedyuk/npm-version@1.1.1
        with:
          version: ${{ github.event.inputs.pkg_version }}
          package: 'web-apps/angular-apps/projects/angular-ui'

      - name: Build Package
        run: cd ./web-apps/angular-apps && yarn run build-angular-ui

      - name: 'Print version'
        run: cd ./web-apps/angular-apps/dist/angular-ui && cat package.json

      - name: Prepare tar file
        run: cd ./web-apps/angular-apps/dist/angular-ui && npm pack

      - name: List files
        run: ls ./web-apps/angular-apps/dist/angular-ui

      - name: Publish package
        run: cd ./web-apps/angular-apps/dist/angular-ui && npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}} 