name: build-service-abstractions

on:

  workflow_dispatch:
    inputs:
      pkg_version:
        description: "Nuget package version"
        required: true
        default: "0.0.0"
      test_mode:
        description: "Flag value of test mode"
        required: false
        default: "true"

jobs:
  build-package:
    runs-on: ubuntu-latest
    
    permissions:
      actions: read
      contents: read
      security-events: write  # Ensure this permission is set

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v4

      - name: echo github ref
        run: echo ${{ github.ref }}

      # - name: Run a one-line script
      #   run: echo Hello, world!

      # dotnet build
      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '8.0.x'  # Specify the .NET version you are using

      - name: Restore dependencies
        run: cd ./Service.Abstractions && dotnet restore

      - name: Build
        run: cd ./Service.Abstractions && dotnet build --configuration Debug --no-restore

      - name: Pack
        run: cd ./Service.Abstractions && dotnet pack -p:PackageVersion=${{ github.event.inputs.pkg_version }} -o bin

      - name: Publish the package to nuget.org
        run: cd ./Service.Abstractions && dotnet nuget push ./bin/*.nupkg -k $NUGET_AUTH_TOKEN -s https://api.nuget.org/v3/index.json
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.NUGET_AUTH_TOKEN }}

      # nuget package
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          pwd